name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8.0.232+9.1
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean && ./gradlew app:assembleDebug
      
    # 上传文件  
    - name: Upload Apk
      uses: actions/upload-artifact@v1
      with: 
        name: qd-info
        path: app/build/outputs/apk/debug/app-debug.apk
        
    # 上传文件到蒲公英    
    - name: Upload File to Pgyer
      run: curl -F 'file=@app/build/outputs/apk/debug/app-debug.apk' -F "_api_key=${{ secrets.API_KEY }}" -F "uKey=${{ secrets.PGYER_USER_KEY }}" -F "buildInstallType=3" https://www.pgyer.com/apiv2/app/upload
        
    # step： 获取apk版本号
    - name: APK Version
      id: apk_version
      run: |
            versionCode=`grep "versionCode" app/build.gradle | awk -F " " '{print $2}'`
            versionName=`grep "versionName" app/build.gradle | awk -F ''\"'' '{print $2}'`
            echo "versionResult=$versionName.$versionCode"  >> $GITHUB_ENV  

    # 获取git log
    - name: Get git log
      id: git_log
      run: |
            updateLog=`git log --pretty=format:"%s" -1`
            echo "updateLog=$updateLog" >> $GITHUB_ENV
            
    # 获取发送者
    - name: Sender
      run: echo "sender=$GITHUB_ACTOR" >> $GITHUB_ENV
        
    # 向钉钉发送消息
    - name: dingtalk
      run: | 
            curl '${{ secrets.DINGDING_WEBHOOK }}' -H 'Content-Type: application/json' -d '{"msgtype": "text", "text": {"content":"吃饭! \n触发人：${{ env.sender }} \n版本：${{ env.versionResult }} \n提交内容：${{ env.updateLog }} \n下载地址：${{ secrets.PGY_URL }}"}}'

    # 发送邮件
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: Github Actions job result
        to: 2556536414@qq.com
        from: TeaOf 
        secure: true
        body: "吃饭! \n触发人：${{ env.sender }} \n版本：${{ env.versionResult }} \n提交内容：${{ env.updateLog }} \n下载地址：${{ secrets.PGY_URL }}"
